export const INDUSTRIES = [
  "Accounting",
  "Advertising & Marketing",
  "Aerospace & Defense",
  "Agriculture",
  "Architecture & Planning",
  "Automotive",
  "Banking & Financial Services",
  "Biotechnology",
  "Broadcasting & Media",
  "Business Consulting",
  "Chemicals",
  "Civil Service / Government",
  "Construction",
  "Consumer Goods",
  "Education",
  "Electronics",
  "Energy & Utilities",
  "Engineering",
  "Entertainment",
  "Environmental Services",
  "Fashion & Apparel",
  "Food & Beverage",
  "Healthcare",
  "Hospitality & Tourism",
  "Human Resources",
  "Information Technology",
  "Insurance",
  "International Trade",
  "Investment Management",
  "Law / Legal Services",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Maritime / Shipping",
  "Mining & Metals",
  "Non-Profit / NGO",
  "Oil & Gas",
  "Pharmaceuticals",
  "Private Equity / Venture Capital",
  "Public Relations",
  "Publishing",
  "Real Estate",
  "Research & Development",
  "Retail",
  "Semiconductors",
  "Sports & Recreation",
  "Telecommunications",
  "Transportation",
  "Venture Capital",
  "Other",
] as const;

export type Industry = (typeof INDUSTRIES)[number];
